name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Setup
        run: curl -sL https://c-naoki.github.io/dotfiles/scripts/bootstrap.sh | sh
